In [1]:
import numpy as np

In [2]:
list_1 = [1, 2, 3, 4, 5]
myarr = np.array(list_1)

In [3]:
myarr

array([1, 2, 3, 4, 5])

In [4]:
myarr.dtype

dtype('int32')

In [6]:
type(myarr)

numpy.ndarray

In [8]:
np.arange(0, 6)

array([0, 1, 2, 3, 4, 5])

In [11]:
np.ones(5) + 9

array([10., 10., 10., 10., 10.])

In [13]:
arr = np.arange(25).reshape(5, 5)

In [14]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
ar = np.random.rand(35).reshape(7, 5)
ar

array([[0.31282949, 0.84808396, 0.87955171, 0.19606562, 0.0631725 ],
       [0.32349803, 0.21565233, 0.97411888, 0.32043212, 0.88767822],
       [0.0382257 , 0.83912132, 0.8814392 , 0.78357671, 0.31598466],
       [0.66756642, 0.46575705, 0.41562368, 0.64473743, 0.1583045 ],
       [0.46002087, 0.24374782, 0.23520669, 0.91927247, 0.69115985],
       [0.92945974, 0.45795367, 0.61933566, 0.9607637 , 0.09191396],
       [0.01259   , 0.72256202, 0.677207  , 0.66962232, 0.19964857]])

In [22]:
a = np.arange(0,30).reshape(6, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [23]:
a[3:, 2:]

array([[17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [26]:

a.sum()

435

In [ ]:
# print('Row sum: ', a.sum(axis = 1))
print('Col sum: ', a.sum(axis = 0))

In [29]:
b = np.arange(0,30)

In [34]:
b = np.arange(1,30)

In [35]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
b_m = b % 3 != 0

In [40]:
b_m

array([ True,  True, False,  True,  True, False,  True,  True, False,
        True,  True, False,  True,  True, False,  True,  True, False,
        True,  True, False,  True,  True, False,  True,  True, False,
        True,  True])

In [41]:
b[b_m]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29])

In [2]:
import pandas as pd

E-Commerce Purchases Exercise

In [3]:
cust = pd.read_csv('Cust_Purch_FakeData.csv')

In [4]:
cust.head()

prefix    first       last              email  gender  age  \
0    Dr.      Ray     Morton    sebvajom@kol.km    Male   38   
1   Miss  Claudia  Rodriquez      acu@jatsot.ug  Female   51   
2   Miss    Harry      Meyer          zuz@lo.wf  Female   51   
3   Miss    Edith    Gilbert  hansohsi@jupec.md  Female   55   
4    Dr.     Lura     Murphy     webediti@je.st  Female   20   

                        company              profession           phone  \
0                Medtronic Inc.        Health Therapist  (987) 619-2695   
1  Ames Department Stores, Inc.        Health Therapist  (356) 736-7352   
2                     CSX Corp.     Political Scientist  (539) 246-1806   
3        Murphy Oil Corporation  Transportation Manager  (984) 962-7494   
4                  PETsMART Inc            Statistician  (902) 568-9748   

    postal province             cc_no   cc_exp                    cc_type  \
0  B6V 3W3       MB  5020000000000230  05/2018                       Solo   
1  G7M 5F3       SK  5020000000000230  07/2028                       Visa   
2  A0Z 6P9       NS  6300000000000000  02/2023                     Switch   
3  P9I 9H3       YT  3530000000000000  02/2028                    Maestro   
4  S1A 6K0       ON  4030000000000000  10/2025  Diners Club International   

   price(CAD) fav_color              ip    weekday ampm        date  
0        8.36      Blue    126.23.139.2     Sunday   pm  04/05/1930  
1       68.31     Black  106.198.76.211    Tuesday   am  12/20/1926  
2       34.65     Black  186.150.187.29  Wednesday   pm  08/20/1931  
3       64.59     White   80.140.57.161   Saturday   am  06/18/2001  
4       20.83    Yellow   211.103.43.41     Friday   pm  06/14/2045

In [5]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 20 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   prefix      30000 non-null  object 
 1   first       30000 non-null  object 
 2   last        30000 non-null  object 
 3   email       30000 non-null  object 
 4   gender      30000 non-null  object 
 5   age         30000 non-null  int64  
 6   company     30000 non-null  object 
 7   profession  30000 non-null  object 
 8   phone       30000 non-null  object 
 9   postal      30000 non-null  object 
 10  province    30000 non-null  object 
 11  cc_no       30000 non-null  int64  
 12  cc_exp      30000 non-null  object 
 13  cc_type     30000 non-null  object 
 14  price(CAD)  30000 non-null  float64
 15  fav_color   30000 non-null  object 
 16  ip          30000 non-null  object 
 17  weekday     30000 non-null  object 
 18  ampm        30000 non-null  object 
 19  date        30000 non-nul

# Max & Min of customer's age?

In [6]:
cust['age'].max()

65

In [7]:
cust['age'].min()

18

In [8]:
cust['age'].mean()                   # avg. age of customers.

41.550066666666666

In [9]:
cust['first'].value_counts().head(3)

Willie     130
Francis    124
Eula        86
Name: first, dtype: int64

In [10]:
cust['phone'].value_counts().head(1)

(263) 382-8004    2
Name: phone, dtype: int64

In [11]:
cust[cust['phone'] == '(263) 382-8004']

prefix  first   last                email  gender  age            company  \
15   Mrs.  Lilly  Tyler      kofadu@itohi.tf  Female   38          CSX Corp.   
16   Mrs.  Peter   Cain  megkosig@anazeor.gn    Male   27  Campbell Soup Co.   

             profession           phone   postal province             cc_no  \
15  Structural Engineer  (263) 382-8004  V7K 1E3       ON    30000000000000   
16   Insurance Adjuster  (263) 382-8004  E8T 2B4       YT  3530000000000000   

     cc_exp                    cc_type  price(CAD) fav_color              ip  \
15  11/2022  Diners Club Carte Blanche        9.61    Yellow   74.124.37.227   
16  03/2024                       Solo       13.74     Black  25.207.141.135   

     weekday ampm        date  
15  Saturday   am  03/30/1985  
16   Tuesday   am  08/05/1950

In [12]:
cust[(cust['profession'] == 'Structural Engineer') & (cust['gender'] == 'Male')].count()

prefix        43
first         43
last          43
email         43
gender        43
age           43
company       43
profession    43
phone         43
postal        43
province      43
cc_no         43
cc_exp        43
cc_type       43
price(CAD)    43
fav_color     43
ip            43
weekday       43
ampm          43
date          43
dtype: int64

In [13]:
cust[(cust['profession'] == 'Structural Engineer') & (cust['gender'] == 'Female') & (cust['province'] == 'AB')]

prefix first      last              email  gender  age  \
8858     Dr.   Roy   Stanley  apiunvo@ehasom.ir  Female   39   
9058     Mr.  Lora   Kennedy    dennap@rabac.se  Female   51   
24736   Mrs.  Nell  Richards          dob@me.ki  Female   18   
29865   Mrs.   Don  McDaniel        naf@zudu.bj  Female   37   

                              company           profession           phone  \
8858       Cincinnati Financial Corp.  Structural Engineer  (876) 758-2929   
9058              BJ Services Company  Structural Engineer  (305) 786-6959   
24736    Telephone & Data Systems Inc  Structural Engineer  (262) 681-5018   
29865  Anadarko Petroleum Corporation  Structural Engineer  (238) 789-2825   

        postal province             cc_no   cc_exp  \
8858   N5A 6L2       AB  6300000000000000  02/2022   
9058   N3R 4B7       AB   201000000000000  06/2019   
24736  N3Y 3G2       AB   347000000000000  07/2028   
29865  B4A 8Q9       AB  5610000000000000  12/2022   

                                  cc_type  price(CAD) fav_color  \
8858                         InstaPayment       31.86       Red   
9058   Diners Club United States & Canada       53.29     Black   
24736                    American Express       76.28      Blue   
29865                          Mastercard       62.71      Blue   

                    ip    weekday ampm        date  
8858    165.249.159.57     Sunday   pm  12/25/1903  
9058    42.216.243.206   Thursday   pm  06/06/2028  
24736     91.16.30.156  Wednesday   pm  07/14/1951  
29865  162.233.117.142     Sunday   pm  11/03/1989

In [14]:
print(cust['price(CAD)'].max())
print(cust['price(CAD)'].min())
print(cust['price(CAD)'].mean())

100.0
0.0
49.990775


In [15]:
cust[cust['cc_exp'].apply(lambda x: x[5:] == '19')]

prefix     first       last              email  gender  age  \
45      Mrs.  Winifred  Henderson     ezamaw@radi.kn  Female   43   
46      Miss   Carolyn     Horton   dehje@mowakbo.tj    Male   22   
49      Miss    Virgie      Adams   lodbinogu@ir.edu    Male   56   
60      Mrs.     Blake       Hart         nup@pov.nc  Female   46   
66      Miss     Leila  Carpenter       ke@wufiol.wf    Male   21   
...      ...       ...        ...                ...     ...  ...   
29952    Mr.     Julia    Elliott  zuruhmu@gevbon.th  Female   18   
29957   Mrs.    Ronald   Stephens          beg@be.sc  Female   29   
29959   Mrs.     Isaac   Guerrero        ji@rofom.ve    Male   21   
29966   Mrs.    Hunter  Rodriguez      zubibil@fo.do  Female   26   
29987    Mr.     Billy      Lucas     hihdu@kuwze.hm  Female   38   

                                company                          profession  \
45                  Western Digital Inc                  Relocation Manager   
46     Stewart & Stevenson Services Inc                    Employment Agent   
49                   Maxtor Corporation                  Systems Programmer   
60              Kindred Healthcare Inc.        Computer Graphics Specialist   
66                    W.W. Grainger Inc                              Artist   
...                                 ...                                 ...   
29952      Gentiva Health Services Inc.               Management Consultant   
29957            McDonald's Corporation                           Geologist   
29959             Johnson Controls Inc.                              Lawyer   
29966                    Pharmacia Corp                  Interior Decorator   
29987                Deluxe Corporation  Organizational Development Manager   

                phone   postal province             cc_no   cc_exp  \
45     (250) 572-7482  K9C 2D2       BC  6300000000000000  12/2019   
46     (737) 647-5446  L1F 9E3       PE  4900000000000000  07/2019   
49     (764) 601-4889  B2O 6Z0       NB  3530000000000000  02/2019   
60     (719) 605-1004  X0O 5E1       PE  5480000000000000  10/2019   
66     (816) 775-3467  E5X 5V9       NS  5140000000000000  11/2019   
...               ...      ...      ...               ...      ...   
29952  (878) 729-1214  C6L 3S8       AB  6010000000000000  05/2019   
29957  (937) 288-1029  V4W 1T1       YT  5170000000000000  06/2019   
29959  (706) 297-1902  B9M 1U5       AB  5610000000000000  10/2019   
29966  (874) 494-4542  K1M 8T0       AB  3530000000000000  09/2019   
29987  (933) 517-6356  K6I 2U5       QC    36400000000000  03/2019   

                         cc_type  price(CAD) fav_color               ip  \
45                         Laser       99.49      Blue    196.43.87.187   
46                  InstaPayment       44.46    Yellow  135.153.126.179   
49     Diners Club Carte Blanche       66.05       Red  175.149.148.141   
60                  InstaPayment       89.87     White   164.16.206.229   
66                 Visa Electron       29.63     Green   99.203.101.232   
...                          ...         ...       ...              ...   
29952  Diners Club International       42.49      Blue    42.62.136.183   
29957              Discover Card       17.32       Red    46.127.70.118   
29959        Diners Club enRoute       26.69     White   207.217.50.132   
29966               InstaPayment       62.58     Green   108.20.175.201   
29987               InstaPayment       21.17      Blue       72.8.98.51   

         weekday ampm        date  
45     Wednesday   pm  07/21/2051  
46     Wednesday   pm  07/25/2010  
49        Monday   am  05/15/2047  
60        Sunday   am  05/05/1942  
66       Tuesday   am  01/28/1936  
...          ...  ...         ...  
29952   Saturday   am  10/17/2063  
29957     Monday   pm  12/05/1913  
29959     Monday   pm  01/25/1958  
29966    Tuesday   am  09/10/1918  
29987    Tuesday   pm  05/18/1929  

[2684 rows x 20 columns]

In [21]:
cust[cust['cc_type'] == 'Visa'].count()

prefix        1721
first         1721
last          1721
email         1721
gender        1721
age           1721
company       1721
profession    1721
phone         1721
postal        1721
province      1721
cc_no         1721
cc_exp        1721
cc_type       1721
price(CAD)    1721
fav_color     1721
ip            1721
weekday       1721
ampm          1721
date          1721
dtype: int64

In [25]:
cust[cust['email'].apply(lambda x: x.split('@')[1]) == 'am.edu']

prefix    first      last         email  gender  age  \
150   Miss  Loretta  Fletcher  barit@am.edu  Female   48   

                     company                profession           phone  \
150  York International Corp  Rehabilitation Counselor  (323) 279-8038   

      postal province             cc_no   cc_exp  \
150  E5X 8L0       QC  6330000000000000  05/2021   

                                cc_type  price(CAD) fav_color              ip  \
150  Diners Club United States & Canada       97.26     White  147.57.240.225   

    weekday ampm        date  
150  Monday   am  11/07/2066

Q. Which day of the week, the store gets more customer's?

NameError: name 'cust' is not defined